FROM amazonlinux
RUN yum install -y unzip
RUN curl -o daemon.zip https://s3.dualstack.us-east-1.amazonaws.com/aws-xray-assets.us-east-1/xray-daemon/aws-xray-daemon-linux-2.x.zip
RUN unzip daemon.zip && cp xray /usr/bin/xray
ADD deploy/xray/cfg.yaml /etc/xray-daemon.yaml
CMD ["/usr/bin/xray", "-c", "/etc/xray-daemon.yaml"]
EXPOSE 2000/udp
