FROM ubuntu
RUN apt-get update && apt-get install -y \
	build-essential \
	git \
	curl \
	sudo \
	apt-transport-https \
  ca-certificates \
  software-properties-common

RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN apt-get install -y nodejs
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py --user
RUN ~/.local/bin/pip install awscli --upgrade --user
RUN ~/.local/bin/pip install awsebcli --upgrade --user

RUN curl -L -o /tmp/docker-17.03.0-ce.tgz https://get.docker.com/builds/Linux/x86_64/docker-17.03.0-ce.tgz
RUN tar -xz -C /tmp -f /tmp/docker-17.03.0-ce.tgz
RUN mv /tmp/docker/* /usr/bin

RUN curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` > /tmp/docker-compose
RUN mv /tmp/docker-compose /usr/bin/docker-compose
RUN chmod +x /usr/bin/docker-compose

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN sudo apt update; apt-get install yarn

RUN npm install sass -g

ENV PATH "$PATH:/root/.local/bin/:/usr/local/bin"
