version: '2'

services:
  "mongo":
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - data_mongo:/data/db
      - data_logs:/data/logs
    ports:
      - 27017:27017
    networks:
      - frontend

  "webapp-antisocial":
    image: 980978009426.dkr.ecr.us-east-1.amazonaws.com/anti-social-development:webapp-antisocial
    container_name: webapp-antisocial
    ports:
      - "3000:3000"
    volumes:
      - data_uploads:/var/app/current/client/uploads
    networks:
      - frontend
    env_file: ~/antisocial-docker-mongo.env
networks:
  frontend:

volumes:
  data_uploads:
    external:
      name: uploads
  data_mongo:
    external:
      name: mongo-data
  data_logs:
    external:
      name: mongo-logs
